version: '2.1'
services:
  bwdb:
    build:
      context: ./Docker
      dockerfile: Dockerfile.db
    image: bw/db
    environment:
      sa_password: "29hHzGtB"
      ACCEPT_EULA: "Y"
  bwweb:
    build:
      context: ./Docker
      dockerfile: Dockerfile.web
    image: bw/web
    depends_on:
      - "bwdb"
    
networks:
  default:
    external:
      name: nat
