name: Performance Comparison

on:
  pull_request:
    branches:
      - master

    paths:
      - 'src/Saritasa.Tools.CodeAnalyzers/**'
  
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compare-performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch (Current Changes)
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 'Install PowerUtils.BenchmarkDotnet.Reporter'
        run: dotnet tool install --global PowerUtils.BenchmarkDotnet.Reporter

      - name: 'Restore dependencies'
        run: dotnet restore

      - name: 'Run benchmarks compare'
        run: pbreporter compare -b ./artifacts-base/results/Saritasa.Tools.CodeAnalyzers.Benchmarks.CodeAnalyzersBenchmarks-report-full-compressed.json -t ./artifacts-pr/results/Saritasa.Tools.CodeAnalyzers.Benchmarks.CodeAnalyzersBenchmarks-report-full-compressed.json -f markdown -f console

      - name: Read file content
        run: ls ./BenchmarkReporter
        


