name: Performance Comparison

on:
  pull_request:
    branches:
      - master

    paths:
      - 'src/Saritasa.Tools.CodeAnalyzers/**'
  
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compare-performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch (Current Changes)
        uses: actions/checkout@v4
    
      - name: Store and Compare Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1.22.1
        with:
          tool: 'benchmarkdotnet'
          output-file-path: ./artifacts-pr/results/Saritasa.Tools.CodeAnalyzers.Benchmarks.CodeAnalyzersBenchmarks-report-full-compressed.json
          external-data-json-path: ./artifacts-base/results/Saritasa.Tools.CodeAnalyzers.Benchmarks.CodeAnalyzersBenchmarks-report-full-compressed.json
          summary-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          save-data-file: false
          comment-on-alert: true
        


