version: '2.1'
services:
  db:
    build:
      context: ./Docker
      dockerfile: Dockerfile.db
    environment:
      sa_password: "29hHzGtB"
      ACCEPT_EULA: "Y"
    networks:
      - default
  web:
    build:
      context: ./Docker
      dockerfile: Dockerfile.web
    depends_on:
      - "db"
    ports:
      - "5001:80"
    volumes:
      - "temp:C:/Temp2"
    
networks:
  default:
    external:
      name: nat

volumes:
  temp:

