version: '2.1'
services:
  db:
    build:
      context: ./Docker
      dockerfile: Dockerfile.db
    image: zerg/db
    environment:
      sa_password: "29hHzGtB"
      ACCEPT_EULA: "Y"
    hostname: zergdb
  web:
    build:
      context: ./Docker
      dockerfile: Dockerfile.web
    image: zerg/web
    depends_on:
      - "db"
    ports:
      - "8080:80"
    volumes:
      - "temp:C:/Temp2"
    hostname: zergweb
    
networks:
  default:
    external:
      name: nat

volumes:
  temp:
